# Generated by Django 4.1.7 on 2024-02-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VC', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('VV', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('PT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product_table')),
            ],
        ),
    ]
